[tool.poe.tasks.add-editable-hyfi]
shell = """
  poetry remove hyfi
  poetry add --group dev --editable ../hyfi
"""
help = "Add hyfi as an editable dependency"

[tool.poe.tasks.copy-hyfi-conf]
shell = """
  hyfi cmd=cpcfg copier.dst_path=src/hyfi_template/conf copier.exclude='**/*/about/__init__.yaml'
"""
help = "Copy hyfi conf to src/hyfi_template/conf"

[tool.poe.tasks.apply-hyfi-template]
cmd = """
  copier --answers-file .copier-hyfi-config.yaml gh:entelecheia/hyfi-template .
"""
use_exec = true
help = "Apply hyfi template"
